# Generated by Django 2.1.7 on 2019-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_voted_id',
            field=models.IntegerField(default=0),
        ),
    ]
