# Generated by Django 2.1.7 on 2019-03-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_voted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_voted_id',
            field=models.IntegerField(default=1),
        ),
    ]
