# Generated by Django 2.1.7 on 2019-03-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190319_1745'),
        ('users', '0003_auto_20190319_1811'),
    ]

    operations = [
    ]
