# Generated by Django 2.1.7 on 2019-03-05 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('UK', 'Unkown'), ('GS', 'German Shepherd'), ('DM', 'Dobermann'), ('DH', 'Dachshund')], default='Unkown', max_length=20)),
                ('rating', models.FloatField(default=0)),
                ('picture', models.ImageField(upload_to='MEDIA_ROOT', verbose_name='img')),
                ('votes', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
