# Generated by Django 2.1.7 on 2019-03-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('1', 'Affenpinscher'), ('2', 'Afghan Hound'), ('3', 'Airedale Terrier'), ('4', 'Alaskan Malamute'), ('5', 'American Staffordshire Bull Terrier'), ('6', 'Anatolian Shepherd Dog'), ('7', 'Australian Cattle Dog'), ('8', 'Australian Kelpie'), ('9', 'Australian Shepherd Dog'), ('10', 'Australian Silky Terrier'), ('11', 'Australian Terrier'), ('12', 'Basenji'), ('13', 'Basset Fauve de Bretagne'), ('14', 'Basset Hound'), ('15', 'Beagle'), ('16', 'Bearded Collie'), ('17', 'Bedlington Terrier'), ('18', 'Belgian Shepherd Dog Groenendael'), ('19', 'Belgian Shepherd Dog Laekenois'), ('20', 'Belgian Shepherd Dog Malinois'), ('21', 'Belgian Shepherd Dog Tervueren'), ('22', 'Bernese Mountain Dog'), ('23', 'Bichon Frise'), ('24', 'Bloodhound'), ('25', 'Border Collie'), ('26', 'Border Terrier'), ('27', 'Borzoi'), ('28', 'Boston Terrier'), ('29', 'Bouvier des Flandres'), ('30', 'Boxer'), ('31', 'Bracco Italiano'), ('32', 'Briard'), ('33', 'Brittany'), ('34', 'Bull Terrier'), ('35', 'Bull Terrier Miniature'), ('36', 'Bulldog'), ('37', 'Bullmastiff'), ('38', 'Cairn Terrier'), ('39', 'Cavalier King Charles Spaniel'), ('40', 'Cesky Terrier'), ('41', 'Chesapeake Bay Retriever'), ('42', 'Chihuahua (Smooth Coat)'), ('43', 'Chinese Crested'), ('44', 'Chow Chow (Smooth)'), ('45', 'Clumber Spaniel'), ('46', 'Collie (Rough)'), ('47', 'Collie (Smooth)'), ('48', 'Curly-Coated Retriever'), ('49', 'Dachshund (Miniature Long Haired)'), ('50', 'Dachshund (Miniature Smooth Haired)'), ('51', 'Dachshund (Miniature Wire Haired)'), ('52', 'Dachshund (Smooth Haired)'), ('53', 'Dachshund (Wire Haired)'), ('54', 'Dalmatian'), ('55', 'Dandie Dinmont Terrier'), ('56', 'Deerhound'), ('57', 'Dobermann'), ('58', 'Dogue de Bordeaux'), ('59', 'English Setter'), ('60', 'English Springer Spaniel'), ('61', 'English Toy Terrier (Black & Tan)'), ('62', 'Field Spaniel'), ('63', 'Finnish Lapphund'), ('64', 'Finnish Spitz'), ('65', 'Flat-Coated Retriever'), ('66', 'Fox Terrier Smooth Coat'), ('67', 'Fox Terrier Wire Coat'), ('68', 'Foxhound'), ('69', 'French Bulldog'), ('70', 'German Shepherd Dog'), ('71', 'German Short-Haired Pointer'), ('72', 'German Spitz Klein'), ('73', 'German Wire-Haired Pointer'), ('74', 'Golden Retriever'), ('75', 'Gordon Setter'), ('76', 'Great Dane'), ('77', 'Greyhound'), ('78', 'Harrier Hound'), ('79', 'Hungarian Vizsla'), ('80', 'Hungarian Wire-Haired Vizsla'), ('81', 'Ibizan Hound'), ('82', 'Irish Setter'), ('83', 'Irish Terrier'), ('84', 'Irish Water Spaniel'), ('85', 'Irish Wolfhound'), ('86', 'Italian Greyhound'), ('87', 'Japanese Akita'), ('88', 'Japanese Chin'), ('89', 'Japanese Spitz'), ('90', 'Keeshond'), ('91', 'Kerry Blue Terrier'), ('92', 'King Charles Spaniel'), ('93', 'Labradoodle'), ('94', 'Labrador Retriever'), ('95', 'Lakeland Terrier'), ('96', 'Leonberger'), ('97', 'Lhaso Apso'), ('98', 'Lowchen'), ('99', 'Maltese'), ('100', 'Manchester Terrier'), ('101', 'Maremma Sheepdog'), ('102', 'Mastiff'), ('103', 'Newfoundland'), ('104', 'Norfolk Terrier'), ('105', 'Norwich Terrier'), ('106', 'Nova Scotia Duck Tolling Retriever'), ('107', 'Old English Sheepdog'), ('108', 'Papillon'), ('109', 'Parson Jack Russell Terrier'), ('110', 'Pharaoh Hound'), ('111', 'Pointer'), ('112', 'Pomeranian'), ('113', 'Poodle Miniature'), ('114', 'Poodle Standard'), ('115', 'Poodle Toy'), ('116', 'Portuguese Water Dog'), ('117', 'Pug'), ('118', 'Pyrenean Mountain Dog'), ('119', 'Rhodesian Ridgeback'), ('120', 'Rottweiler'), ('121', 'Saluki'), ('122', 'Samoyed'), ('123', 'Schipperke'), ('124', 'Schnauzer Giant'), ('125', 'Schnauzer Miniature'), ('126', 'Schnauzer Standard'), ('127', 'Scottish Terrier'), ('128', 'Shar Pei'), ('129', 'Shetland Sheepdog'), ('130', 'Shih Tzu'), ('131', 'Siberian Husky'), ('132', 'Skye Terrier'), ('133', 'Sloughi'), ('134', 'Soft Coated Wheaten Terrier'), ('135', 'St Bernard'), ('136', 'Sussex Spaniel'), ('137', 'Swedish Vallhund'), ('138', 'Tenterfield Terrier'), ('139', 'Tibetan Mastiff'), ('140', 'Tibetan Spaniel'), ('141', 'Tibetan Terrier'), ('142', 'Weimaraner'), ('143', 'Welsh Corgi (Cardigan)'), ('144', 'Welsh Corgi (Pembroke)'), ('145', 'Welsh Springer Spaniel'), ('146', 'Welsh Terrier'), ('147', 'West Highland White Terrier'), ('148', 'Whippet'), ('149', 'Yorkshire Terrier')], default='', max_length=100)),
                ('score', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
                ('picture', models.FileField(blank=True, null=True, upload_to='dog_pics/')),
                ('votes', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('text', models.TextField(max_length=240)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestboy.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
