# Generated by Django 2.1.7 on 2019-03-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='average',
            field=models.FloatField(default=0),
        ),
    ]
