# Generated by Django 2.1.7 on 2019-03-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0002_dog_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.ImageField(upload_to='bestboy/dog_pics/', verbose_name='img'),
        ),
    ]
