# Generated by Django 2.1.7 on 2019-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0002_dog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(choices=[('UK', 'Unkown'), ('GS', 'German Shepherd'), ('DM', 'Dobermann'), ('DH', 'Dachshund')], default='Unkown', max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='picture',
            field=models.ImageField(blank=True, upload_to='MEDIA_ROOT', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='dog',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
