# Generated by Django 2.1.7 on 2019-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0003_auto_20190302_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.ImageField(upload_to='MEDIA_ROOT', verbose_name='img'),
        ),
    ]
