# Generated by Django 2.1.7 on 2019-03-19 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestboy', '0004_auto_20190319_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='average',
        ),
        migrations.AddField(
            model_name='score',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestboy.Dog'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
