# Generated by Django 2.1.7 on 2019-03-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0007_auto_20190302_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
