# Generated by Django 2.1.7 on 2019-03-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0007_auto_20190319_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='text',
            field=models.TextField(max_length=3000),
        ),
    ]
