# Generated by Django 2.1.7 on 2019-03-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0008_dog_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='owner',
        ),
    ]
