# Generated by Django 2.1.7 on 2019-03-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestboy', '0008_auto_20190319_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='average',
            field=models.FloatField(default=0),
        ),
    ]
